### ISSUE TITLE
Ability to add custom layers

### ISSUE THREAD

**Issue by vloncar** [fastmachinelearning/hls4ml#169]
This is already possible through the API, but we should also expose it through `hls4ml` tool. So the user would specify his implementation of a layer, a config and function call template and the C++ code.

**Comment by adas1994** [comment]
Hello Experts, I wanted to contribute to the project and wanted to started with a good open issue. I stumbled upon this one but could not understand much from the description. @vloncar Can you please elaborate on this more?

**Comment by jmduarte** [comment]
Started with #528
