### ISSUE TITLE
something about pytorch model

### ISSUE THREAD

**Issue by mk123qwe** [fastmachinelearning/hls4ml#175]
In my model，there are some tensor torch.cat, torch.transpose,view,torch.mm,and IF condition,most linear layer.
I am not sure wether these function have added into hls4ml.

**Comment by vloncar** [comment]
Current PyTorch converter is very limited and supports only simple fully connected architectures. You can try converting it to ONNX, however, in our experience, manipulations of PyTorch view result in complicated ONNX operations that are not supported.
