### ISSUE TITLE
hls4ml 0.3.0 with pip for Python 2.x gives error

### ISSUE THREAD

**Issue by Tommaso93** [fastmachinelearning/hls4ml#226]
Hello, I tried to install the hls4ml v0.3.0 using the `pip install hls4ml` command (with python 2.x).
During the installation I had the following error:
```
with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```
In order to fix this, I manually downloaded the source code and modified the setup.py, changing 
```
open(path.join(this_directory, 'README.md'), encoding='utf-8')
```
with
```
import io
io.open(path.join(this_directory, 'README.md'), encoding='utf-8')
```
and then running the pip command inside the source code main folder.

**Comment by Tommaso93** [comment]
Edit: After this procedure, several import errors show up when executing:
```
import hls4ml
```

**Comment by Duchstf** [comment]
Can you tried commenting those lines out and do `pip install .` from the source code main directory? Also what are the errors when importing?

**Comment by vloncar** [comment]
Python 2 is not supported. We dropped compatibility before 0.2.0. Python 2 language is EOL since 1.1.2020., you should consider upgrading your flow to Python3.

**Comment by Tommaso93** [comment]
Ok, no problem! I saw the compatibility in the readme, so I though that it could work! 

Thank you,
Tommaso

**Comment by vloncar** [comment]
@Tommaso93 Where did you find the compatibility note in the documentation? We may have missed that one ;-)

**Comment by Tommaso93** [comment]
In the python badge on the readme. Also in the pypi website.

**Comment by vloncar** [comment]
Thanks, we'll update those!

**Comment by Duchstf** [comment]
@vloncar I think it's because of these lines:

https://github.com/hls-fpga-machine-learning/hls4ml/blob/63b12c1493e118f92bdd4fff18aafdc99e1e0de0/setup.py#L39-L40

I can make a PR to fix this later.
