### ISSUE TITLE
User defined unrolling.

### ISSUE THREAD

**Issue by husnainmubarik** [fastmachinelearning/hls4ml#232]
Is it possible to unroll only parameters of network (weights)? Like unroll the network in such a way that one DSP is assigned to each weight value then input feature maps are broadcasted to the specific DSP for mac operation?

**Comment by nhanvtran** [comment]
A full unroll corresponds to a reuse factor of 1 in hls4ml configuration.  See:
https://arxiv.org/abs/1804.06913

See section 2.3, "Parallelization"
