### ISSUE TITLE
Pre-synthesis fails on hls4ml 0.4.0

### ISSUE THREAD

**Issue by rajeshpandit107** [fastmachinelearning/hls4ml#236]
![error](https://user-images.githubusercontent.com/62842121/98295150-1e32af80-1fd7-11eb-9611-0210887f7ec6.png)

Synthesizing a dense model for mnist with 128*128*128*10 architecture with a reuse factor of 200. Pre-synthesis fails

**Comment by nhanvtran** [comment]
What did you set as the `Strategy`?  For a model of this size you should use `Resource`

**Comment by rajeshpandit107** [comment]
I used the strategy as resource, getting the same error still.
![image](https://user-images.githubusercontent.com/62842121/98407523-d45cce80-2095-11eb-9c6c-013939da005d.png)

**Comment by vloncar** [comment]
CNNs in 0.4.0 work only for very small models. You'll have to wait for 0.5.0 which will come after #220 is merged

**Comment by rajeshpandit107** [comment]
synthesis completes with version 0.3.0 with same configuration, could you please suggest the solution?

**Comment by vloncar** [comment]
How do you set the Strategy to "resource"? I can't suggest a solution if you don't provide the code that fails.

**Comment by rajeshpandit107** [comment]
config['Model']['Strategy'] = 'resource'

**Comment by vloncar** [comment]
It works for me.

>  I can't suggest a solution if you don't provide the code that fails.

^ this

**Comment by rajeshpandit107** [comment]
Hi, 
I am providing the jupter-notebook code and vivado_hls log file. I have an architecture of 128*128*128*10 . Pre-synthesis fails on loop unrolling. Could you please provide the solution?

Thanks.
[vivado_hls.log](https://github.com/fastmachinelearning/hls4ml/files/5522459/vivado_hls.log)
[jupyter_notebook_code.txt](https://github.com/fastmachinelearning/hls4ml/files/5522460/jupyter_notebook_code.txt)

**Comment by rajeshpandit107** [comment]
I increased the reuse factor to 2000 and it worked.
