### ISSUE TITLE
No grey boxes in profiling graph 

### ISSUE THREAD

**Issue by DelonShen** [fastmachinelearning/hls4ml#271]
My csim results for my model are coming out a bit funky so I was profiling my model and found that the "Distribution of (non-zero) weights" graph generated by hls4ml.model.profiling.numerical had no grey boxes 

This also happens when I run part 2 of the [hls4ml-tutorial](https://github.com/fastmachinelearning/hls4ml-tutorial/blob/master/part2_advanced_config.ipynb) and I think these two might be caused by the same thing. Graph for part2 of hls4ml-tutorial is below. From what I understand from the [profiling reference](https://fastmachinelearning.org/hls4ml/api/PROFILING.html) since we pass a keras model, hlsmodel, and data there should be grey boxes in here

![index](https://user-images.githubusercontent.com/10728187/104048425-16f86f80-51db-11eb-9cfc-cf8fbe6893c2.png)
 

Distribution of (non-zero) activations graphs seems fine. Is this problem reproducible for other people?

**Comment by vloncar** [comment]
Addressed in #277

**Comment by DelonShen** [comment]
Thank you!
