### ISSUE TITLE
Uses of granularity

### ISSUE THREAD

**Issue by rajeshpandit107** [fastmachinelearning/hls4ml#279]
Can someone please explain the use of granularity while defining the model configuration?

**Comment by vloncar** [comment]
Configuration is meant to be tweaked. You decide how deep you want to go with tweaking. Maybe you just want to specify one precision for the whole model, or maybe you want to specify that one particular layer is going to use specific precision to store intermediate multiplication values. Granularity helps with making that initial configuration.

**Comment by rajeshpandit107** [comment]
Can We synthesize a single layer of a given model(for example first convolution layer of Lenet 5 architecture)  using 'name' or 'type' granularity or any other method?

**Comment by vloncar** [comment]
hls4ml synthesizes whole models, if you only want to synthesize one layer, create a model with only one layer.

**Comment by rajeshpandit107** [comment]
Thanks for that quick reply.
How much time did it take to synthesize a large CNN model in version 0.5.0 version of hls4ml(The CNN model that has been given as reference in the second published paper of hls4ml) ?
![image](https://user-images.githubusercontent.com/62842121/107937052-6df71e80-6fa9-11eb-96fc-816b1dcf19a1.png)

**Comment by thaarres** [comment]
Hi @rajeshpandit107! The model takes roughly 45-90 minutes to synthesise, depending on your CPU.

**Comment by rajeshpandit107** [comment]
hi @thaarres , I am trying to regenerate a similar cnn model, but my synthesis neither completes nor gives any error, it gets stuck for 4-5 days. Could you please help me with the way to define synthesis configuration ?

**Comment by rajeshpandit107** [comment]
I am using a 3 GHz intel Xeon CPU with a ram of 32GB

**Comment by thaarres** [comment]
Hi @rajeshpandit107. This sounds strange. Could you provide further details on what your model is/what your hls4ml configuration is set to? You can find an example configuration at

[https://github.com/thaarres/hls4ml_cnns/blob/master/doScans.py#L61 ](url)

**Comment by rajeshpandit107** [comment]
Hi @thaarres , I tried re-synthesizing the model, I could not succeed. Could you please see the configuration file and point out the incorrect configuration paramters
[vivado_hls.log](https://github.com/fastmachinelearning/hls4ml/files/6114872/vivado_hls.log)
[model.py.log](https://github.com/fastmachinelearning/hls4ml/files/6114878/model.py.log)

**Comment by thaarres** [comment]
Hi @rajeshpandit107 !
You need to set `cfg['IOType']     = 'io_stream'`.
See example at
https://github.com/thaarres/hls4ml_cnns/blob/master/doScans.py#L49
