### ISSUE TITLE
Update documentation to reflect supported Vivado versions

### ISSUE THREAD

**Issue by ynozik** [fastmachinelearning/hls4ml#356]
In documentation, for example [here](https://fastmachinelearning.org/hls4ml/status.html) and [in the main readme](https://github.com/fastmachinelearning/hls4ml) it is stated that Vivado versions since 2018.2 are supported. However this is apparently no longer the case, e.g. due to the use of the STABLE pragma.

**Comment by jmduarte** [comment]
Stable pragma was removed in #351
