### ISSUE TITLE
Does HLS4ML support Tensorflow (without Keras) in Conv2D/Conv1D??

### ISSUE THREAD

**Issue by IanCheng18** [fastmachinelearning/hls4ml#396]
Does HLS4ML support Tensorflow (without Keras) in Conv2D/Conv1D?
I didn't see any converters for TensorFlow instead, but there is a lot for Keras.

I gave up using Keras since I am using lambda layer, or is there any good workaround?

Many thanksssssss

**Comment by thesps** [comment]
Hi, yes there is a [TensorFlow converter](https://github.com/fastmachinelearning/hls4ml/blob/master/hls4ml/converters/tf_to_hls.py). However you will find that a `lambda` operation is not supported - hls4ml cannot generate HLS from arbitrary functions. I'd recommend you try to implement what you need from only the supported layers (try `print(hls4ml.converters.get_supported_keras_layers())`). If you still need to do something very custom, the process to support a custom layer through hls4ml conversion is to: 

- Write a [custom layer in Keras](https://keras.io/guides/making_new_layers_and_models_via_subclassing/) 
- Implement the HLS function that performs the same operation. Take inspiration from the existing nnet_utils implementations. Isolate things that can be configured into a `struct` of configuration settings.
- Implement a class to represent its attributes that inherits from hls4ml [Layer](https://github.com/fastmachinelearning/hls4ml/blob/master/hls4ml/model/hls_layers.py#L345), add it to the [layer map](https://github.com/fastmachinelearning/hls4ml/blob/master/hls4ml/model/hls_layers.py#L1840)
- Register it along with its HLS template ([for example here](https://github.com/fastmachinelearning/hls4ml/blob/master/hls4ml/templates/vivado_template.py))
- Add a conversion handler for it to extract the relevant attributes ([for example here](https://github.com/fastmachinelearning/hls4ml/blob/master/hls4ml/converters/keras/core.py#L9-:21))
