### ISSUE TITLE
GlobalPooling1D broken

### ISSUE THREAD

**Issue by jmduarte** [fastmachinelearning/hls4ml#398]
See discussion on Google Group: https://groups.google.com/g/hls4mlhelp/c/DI5o7FLZQS0/m/ChidBM-WBAAJ?utm_medium=email&utm_source=footer&pli=1

GlobalPooling1D layers are currently broken due to 
(1) bad parsing of inputs in conversion/initialization
(2) missing HLS implementations for `io_stream` and `io_parallel`

```python
~/work/hls4ml/hls4ml/model/hls_layers.py in initialize(self)
   1205 class GlobalPooling1D(Layer):
   1206     def initialize(self):
-> 1207         shape = [self.attributes['n_out'], self.attributes['n_filt']]
   1208         dims = ['N_OUTPUTS_{}'.format(self.index), 'N_FILT_{}'.format(self.index)]
   1209         self.add_output_variable(shape, dims)

KeyError: 'n_out'
```

**Comment by thesps** [comment]
Resolved now #399 is merged?
