### ISSUE TITLE
Compilation error with concatenate layer

### ISSUE THREAD

**Issue by rdhen3** [fastmachinelearning/hls4ml#415]
Hi there, I have just started using hls4ml a couple of days ago with the hope of applying it to a simple SSD inspired CNN. 
The model involves some number >= 0 of convolutional feature extraction layers well as several parallel sets of predictor layers whose outputs needs to be concatenated together. 

A simple version of the model has the following keras summary:
![image](https://user-images.githubusercontent.com/88073332/136896961-f9a25ee4-3748-4bd3-a27a-c70fde3e268f.png)

The current stable build seems to have issues in processing concatenate layers in that i think the shape is incorrectly inferred leading to an IndexError in `hls4ml/model/hls_layers.py`:
```
   1380         axis = self.attributes['axis']
   1381         shape = inp1.shape[:]
-> 1382         shape[axis] += inp2.shape[axis]
   1383         rank = len(shape)
   1384         if rank > 1:

IndexError: list index out of range
```

I tried pulling the latest master upon seeing issue #361 and it seems that the shape/indexing problem was solved by this and is get the following hls4ml summary of the model:
![image](https://user-images.githubusercontent.com/88073332/136898001-38bc231a-eccb-477f-9596-0a747f9c19ca.png)
which seems to match up to the original model correctly. 

However, now I have hit a compilation error when building/compiling the model:
![image](https://user-images.githubusercontent.com/88073332/136898331-0f4d589b-0616-48c6-81a8-6ff3dcb0dc14.png)

I thought perhaps this related to the update going on in #402 so I tried swapping to that branch and trying again but received an identical error. Any thoughts?

**Comment by jmduarte** [comment]
@rdhen3 can you provide a script to reproduce the error? I do believe the latest error is related to issues being addressed in #402.

Also, to confirm are you using `io_stream` or `io_parallel`?

**Comment by rdhen3** [comment]
Indeed I did notice the behaviour of unrolling the output to 1D. Is this done in the same way as, say, a keras `Flatten` layer, or by extension the same as `numpy.reshape`? 
I believe I could indeed remove the `Reshape` layer but would still need to implement it outside the network the output at some point in order to decode the predictions correctly.

**Comment by jmduarte** [comment]
Yes, in your particular case, I would do this:
```python
model = Model(inputs=x, outputs=classes_boxes)
...
keras_prediction = model.predict(X_input).reshape((X_input.shape[0], 16, 6))
...
hls_prediction = hls_model.predict(X_input).reshape((X_input.shape[0], 16, 6))
```
