### ISSUE TITLE
Vivado HLS generating multiple output streams

### ISSUE THREAD

**Issue by LordScarface** [fastmachinelearning/hls4ml#417]
Hello again,

when synthesizing my design, Vivado HLS breaks up the result vector into individual AXI streams. I would assume that the intended behavior would be to have one input and one output stream to the IP Core.

In my mnist example, HLS generates 10 individual AXI streams for the return Values:
![image](https://user-images.githubusercontent.com/18120145/137526336-408e1a77-5806-4f78-b844-dad124045e7e.png)

I've also seen my other projects behave in the same way. Is this an issue with the Vivado HLS Version I'm using (2020.1) or do I have something configured incorrectly in Vivado HLS?

I would appreciate some help with this,
Best Regards,
Lukas

**Comment by bo3z** [comment]
Can you try out the Vitis Accelerator (#991) or Coyote Accelerator backends (#1347). They work with Vitis backends.

**Comment by bo3z** [comment]
They are not merged yet. You will have to check out the branch from the respective PRs mentioned above and install hls4ml locally (by doing cd hls4ml && pip install .)

**Comment by bhitesh311** [comment]
I did that. But I guess only alveo-u55c is supported. I happen to use PYNQ-Z2.
