### ISSUE TITLE
HLS4ML and Vivado hls Synthesis problem with Windows implementation

### ISSUE THREAD

**Issue by Pythagoras21** [fastmachinelearning/hls4ml#426]
HI, i have followed all the steps in the fastmachinelearning. However i have encountered a problem while trying to
1. Build my Vivdao Project.
2. if i manually go to vivado and build the project and rerun , the C simulation failed.
##  **Please Help**  
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

These are the steps i did:  i ran these code in jupyter notebook
===============================================================
1.

import hls4ml
#Fetch a keras model from our example repository
#This will download our example model to your working directory and return an example configuration file
config = hls4ml.utils.fetch_example_model('KERAS_3layer.json')

print(config) #You can print it to see some default parameters

#Convert it to a hls project
hls_model = hls4ml.converters.keras_to_hls(config)

hls_model.build()

#Print out the report if you want
hls4ml.report.read_vivado_report('my-hls-test')

==========================================================
When i run the cell, the output is as follows
==========================================================

Downloading example model files ...
{'OutputDir': 'my-hls-test', 'ProjectName': 'myproject', 'XilinxPart': 'xcku115-flvb2104-2-i', 'ClockPeriod': 5, 'Backend': 'Vivado', 'IOType': 'io_parallel', 'HLSConfig': {'Model': {'Precision': 'ap_fixed<16,6>', 'ReuseFactor': '1'}}, 'KerasJson': 'KERAS_3layer.json', 'KerasH5': 'KERAS_3layer_weights.h5'}
Interpreting Model
Topology:
Layer name: input_1, layer type: InputLayer, current shape: [[None, 16]]
Layer name: fc1_relu, layer type: Dense, current shape: [[None, 16]]
Layer name: fc2_relu, layer type: Dense, current shape: [[None, 64]]
Layer name: fc3_relu, layer type: Dense, current shape: [[None, 32]]
Layer name: output_softmax, layer type: Dense, current shape: [[None, 32]]
Creating HLS model
Writing HLS project
Done
Project myproject_prj does not exist. Rerun "hls4ml build -p my-hls-test".
Project myproject_prj does not exist. Rerun "hls4ml build -p my-hls-test".

=========================================================
=========================================================

2.

Also when i run this  code below

#Use Vivado HLS to synthesize the model
#This might take several minutes
hls4ml build -p KERAS_3layer.json
hls_model_test.build()

#Print out the report if you want
hls4ml.report.read_vivado_report('test')

========================================================
Output
========================================================
 File "C:\Users\General\AppData\Local\Temp/ipykernel_12312/858913559.py", line 3
    hls4ml build -p KERAS_3layer.json
           ^
SyntaxError: invalid syntax
========================================================

3.  Since the python command       hls_model.build()      has created the vivado project but my jupyter notebook cannot build it automatically , i use Vivado HLS 2018.3
I decided to build the project manually using command Vivado_hls -f  build_prj.tcl
i get the following error

___________________________________________________________________________________________________________________
C:\Users\General\DNN_test>ls
Flower_Classification  MNIST_test

C:\Users\General\DNN_test>cd Flower_Classification

C:\Users\General\DNN_test\Flower_Classification>ls
Hardware_acc.ipynb             garnet_1layer.json        my-hls-test.tar.gz           qkeras_mnist_dense.tar.gz
KERAS_3layer.json              garnet_1layer_config.yml  qkeras_mnist_cnn.json        qkeras_mnist_dense_config.yml
KERAS_3layer_weights.h5        garnet_1layer_input.dat   qkeras_mnist_cnn_config.yml  qkeras_mnist_dense_weights.h5
KERAS_conv1d_small.json        garnet_1layer_output.dat  qkeras_mnist_cnn_weights.h5
KERAS_conv1d_small_weights.h5  garnet_1layer_weights.h5  qkeras_mnist_dense
Transfer_learning.ipynb        my-hls-test               qkeras_mnist_dense.json

C:\Users\General\DNN_test\Flower_Classification>cd my-hls-test

C:\Users\General\DNN_test\Flower_Classification\my-hls-test>ls
build_lib.sh   firmware           myproject_bridge.cpp  tb_data
build_prj.tcl  hls4ml_config.yml  myproject_test.cpp    vivado_synth.tcl

C:\Users\General\DNN_test\Flower_Classification\my-hls-test>Vivado_hls -f build_prj.tcl

****** Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC v2018.3 (64-bit)
  **** SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
  **** IP Build 2404404 on Fri Dec  7 01:43:56 MST 2018
    ** Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.

source D:/1.Apps/Xilinx_Vivado/Vivado_HLS/Vivado/2018.3/scripts/vivado_hls/hls.tcl -notrace
INFO: [HLS 200-10] Running 'D:/1.Apps/Xilinx_Vivado/Vivado_HLS/Vivado/2018.3/bin/unwrapped/win64.o/vivado_hls.exe'
INFO: [HLS 200-10] For user 'General' on host 'desktop-b4moo96' (Windows NT_amd64 version 6.2) on Thu Oct 28 00:23:38 +0530 2021
INFO: [HLS 200-10] In directory 'C:/Users/General/DNN_test/Flower_Classification/my-hls-test'
INFO: [HLS 200-10] Creating and opening project 'C:/Users/General/DNN_test/Flower_Classification/my-hls-test/myproject_prj'.
INFO: [HLS 200-10] Adding design file 'firmware/myproject.cpp' to the project
INFO: [HLS 200-10] Adding test bench file 'myproject_test.cpp' to the project
INFO: [HLS 200-10] Adding test bench file 'firmware/weights' to the project
INFO: [HLS 200-10] Adding test bench file 'tb_data' to the project
INFO: [HLS 200-10] Creating and opening solution 'C:/Users/General/DNN_test/Flower_Classification/my-hls-test/myproject_prj/solution1'.
INFO: [XFORM 203-101] Allowed max sub elements number after partition is 4096.
INFO: [XFORM 203-1161] The maximum of name length is set into 60.
ERROR: [HLS 200-70] Part 'xcku115' is not installed.
command 'ap_source' returned error code
    while executing
"source [lindex $::argv 1] "
    ("uplevel" body line 1)
    invoked from within
"uplevel \#0 { source [lindex $::argv 1] } "

INFO: [Common 17-206] Exiting vivado_hls at Thu Oct 28 00:23:39 2021...
C:\Users\General\DNN_test\Flower_Classification\my-hls-test>

___________________________________________________________________________________________________________________

i changed the FPGA model manually in the build_prj.tcl but it also cannot be synthesized and returned errors.

**Please help me resolve this issue, also where can i define the target FPGA in the model?**

**Comment by hepkosmos** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-01-03T21:45:17
          
          
            * 메일 제목 : 
Re: [fastmachinelearning/hls4ml] HLS4ML and Vivado hls Synthesis problem with Windows implementation (Issue #426)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
