### ISSUE TITLE
[XFORM 203-504] run time and excessive memory usage in Vivado HLS 2019.2

### ISSUE THREAD

**Issue by samifry** [fastmachinelearning/hls4ml#427]
Hi, 

I'm trying to implement an LSTM network on FPGA. First, I've tried to implement a small lstm network and it worked. Now I'm trying to do the same things with a larger network with stacked lstm layers. At the end of synthesize, after code transformation, this problem appear : 

```
ERROR: [XFORM 203-504] Stop unrolling loop 'Accum1' (firmware/nnet_utils/nnet_dense.h:184) in function 'nnet::dense_latency<ap_fixed<16, 6, (ap_q_mode)5, (ap_o_mode)3, 0>, ap_fixed<16, 6, (ap_q_mode)5, (ap_o_mode)3, 0>, config10_mult2>' because it may cause large runtime and excessive memory usage due to increase in code size. Please avoid unrolling the loop or form sub-functions for code in the loop body.
ERROR: [HLS 200-70] Pre-synthesis failed.
```

That means I try to implement a too large network on a FPGA without enough resources ? I'm trying to do that with a Kintex7 Ultrascale (xcku115-flvb2104-2-i).

I know LSTM networks are not supported by HLS4ML, but I'm working with a prototype and this error appear for other kinds of networks.

It help me if someone can detail this error and if there is an issue to avoid this error without reduce the network.

Thanks in advance!

**Comment by thesps** [comment]
This usually means you need to switch to `Strategy: Resource`, if that's possible with the version you're working with.

**Comment by Pythagoras21** [comment]
Hi, can you please help me fix Vivado installation not found. i have vivado 2019.2 and also specified it

**Comment by samifry** [comment]
> This usually means you need to switch to `Strategy: Resource`, if that's possible with the version you're working with.

Thanks for your reply, I'm currently trying to make different configuration with your advice. It passed, but finished out of RAM for the moment.
