### ISSUE TITLE
Vivado installation / Path not found 

### ISSUE THREAD

**Issue by Pythagoras21** [fastmachinelearning/hls4ml#434]
hi, i have installed Vivado 2019.2 on my computer Ubuntu 20.04.3 LTS. I have installed hls4ml on Google colab.

i have also specified the Vivado installation path 
os.environ['PATH'] = '/home/gegerin/Vivado_HLS/Vivado/2019.2/bin' + os.environ['PATH']

However, when i run the command : hls_model.build()
i get the following output
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Exception                                 Traceback (most recent call last)

<ipython-input-7-37263b86faba> in <module>()
      4 os.environ['PATH'] = '/home/gegerin/Vivado_HLS/Vivado/2019.2/bin' + os.environ['PATH']
      5 
----> 6 hls_model.build()
      7 
      8 #Print out the report if you want

/usr/local/lib/python3.7/dist-packages/hls4ml/model/hls_model.py in build(self, reset, csim, synth, cosim, validation, export, vsynth)
    548                 found = os.system('command -v vivado_hls > /dev/null')
    549                 if found != 0:
--> 550                     raise Exception('Vivado HLS installation not found. Make sure "vivado_hls" is on PATH.')
    551 
    552             elif backend == 'Intel':

Exception: Vivado HLS installation not found. Make sure "vivado_hls" is on PATH.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 

Please help me solve this issue

**Comment by thesps** [comment]
Closing this issue as you've already posted it more than once...
