### ISSUE TITLE
How to use profiling with master branch

### ISSUE THREAD

**Issue by HenningCode** [fastmachinelearning/hls4ml#452]
Hello Guys,

I want to debug my HLS Model with profiling. I also want to use the latest master branch, but if I try to call eg. `hls4ml.model.profiling.numerical` I get this error `module 'hls4ml.model' has no attribute 'profiling'` is there a way to use profiling with the latest version ?

Greetings.

**Comment by vloncar** [comment]
You need to install hls4ml with `profiling` extra, like `pip install hls4ml[profiling]`. This will install the additional packages required by the profiling tools and `hls4ml.model.profiling` will be available.

**Comment by HenningCode** [comment]
Yeah I know, but then I am stuck with `0.5.0` and not with the newest version available right?

**Comment by vloncar** [comment]
`pip install git+https://github.com/fastmachinelearning/hls4ml.git@master#egg=hls4ml` :wink:

**Comment by HenningCode** [comment]
Thanks! I learned something new today :)
