### ISSUE TITLE
Hls_model.build() jupyter notebook output not coming 

### ISSUE THREAD

**Issue by Pythagoras21** [fastmachinelearning/hls4ml#484]
Hi! I recently installed hls4ml on my pc, 

The "**starting** **Vivado" Output **used to come on my laptop but here on the pc,  the cell with code "hls_model.() " Is running but "starting Vivado window is not coming in jupyter notebook" So I have no feedback on whether it's working or not. 

Please help

**Comment by jmduarte** [comment]
If you are running `hls_model.build()` in a jupyter notebook as opposed to a python script, some of the stdout from Vivado HLS is sent to the terminal window that launched the jupyter notebook server.

If you have access to the terminal, you can check there. Or you can look at the generated `vivado_hls.log` file in the HLS project folder. 

You may also be able to redirect it to the jupyter notebook, but I haven't tried this (https://stackoverflow.com/questions/45200375/stdout-redirect-from-jupyter-notebook-is-landing-in-the-terminal)
