### ISSUE TITLE
How to calculate G-ops/s of CNN accelerator

### ISSUE THREAD

**Issue by rtspk** [fastmachinelearning/hls4ml#500]
Hello Everyone. 

I have a CNN network implemented using the hls4ml framework. 
Alot of the papers report Peak Performance in Gops/s. Could you guys please guide me how can I calculate the peak performance of the HLS4ml CNN accelerator ? ( any links/paper/tutorial which can show the calculation would also be good) 

Best regards
Riz

**Comment by jmduarte** [comment]
Hi @rtspk, we've used 

https://github.com/hls4ml-finn-mlperftiny/CIFAR10/blob/main/hls4ml/train.py#L134-L135
