### ISSUE TITLE
I want to deploy my own network model. Which version of tensorflow and keras should I use？

### ISSUE THREAD

**Issue by ZhangYuQAQ** [fastmachinelearning/hls4ml#507]
I met a difficulty. I want to deploy my own network model. Which version of tensorflow and keras should I use? I currently use TF1.14.0 and keras1.14.0, but I can't parse the depthwise conv2d layer successfully.
I used this example - "keras_ conv2d_ model. json". The version of keras given in the JSON file is: "keras_version": "2.0.0", but I didn't find the version of tensorflow corresponding to keras2.0.0. Which version of tensorflow does keras2.0.0 correspond to？

**Comment by jmduarte** [comment]
Hi @ZhangYuQAQ, you should use a more recent version of keras and tensorflow, e.g. tensorflow>=2.6.0
