### ISSUE TITLE
Lost Layers during compilation

### ISSUE THREAD

**Issue by nickshey** [fastmachinelearning/hls4ml#542]
Hello, I am working on compiling a model that uses MaxPooling2D, UpSample2D, Concatenate, Conv2D, and BatchNorm. We were facing problems with the BatchNorm outputs being deleted, but were able to resolve that. Now we have hit the following error and are wondering where these layers are being deleted. Does anyone have any idea what could be happening here?

![Screenshot from 2022-05-05 17-14-19](https://user-images.githubusercontent.com/24383522/167046826-274aae2f-ae3c-432a-b82b-46306e78f3ab.png)
.

**Comment by jmduarte** [comment]
As discussed offline, I think there are at least 2 issues.

(1) the batchnorm layers were being optimized out by an optimizer that would fuse them with the previous layer even when the batchnorm output needs to be used again downstream, and the graph rewiring would not correctly handle this case apparently... a workaround (for now) is to skip this batchnorm fusion

(2) when removing a node (like linear activation), it is only reconnected to the first node that uses it (even if it's used multiple times). fix is #544
