### ISSUE TITLE
How can I check if my FPGA is supported by this platform?

### ISSUE THREAD

**Issue by jayrmh** [fastmachinelearning/hls4ml#556]
Hey, love the idea behind this platform and your constant managing of the repo!

I would like to ask how I can check if Altera Cyclone IV EP4CE115F29C7 FPGA is supported? Thanks!

**Comment by jmduarte** [comment]
Hi @jayrmh thanks for the question. As long as the platform supports Quartus HLS, it should be supported. See the recently merged #245
