### ISSUE TITLE
[Vitis hls] Cannot apply array transformation pragma/directive because of full array load/store.

### ISSUE THREAD

**Issue by Duchstf** [fastmachinelearning/hls4ml#805]
## Quick summary

I was trying to convert a quantized Conv1D model using Vitis HLS, and was seeing this error:

```
ERROR: [HLS 214-384] in function 'void nnet::conv_1d_latency_cl<ap_fixed<9, 3, (ap_q_mode)5, (ap_o_mode)3, 0>, ap_fixed<16, 6, (ap_q_mode)5, (ap_o_mode)3, 0>, config2>(ap_fixed<9, 3, (ap_q_mode)5, (ap_o_mode)3, 0>*, ap_fixed<16, 6, (ap_q_mode)5, (ap_o_mode)3, 0>*, config2::weight_t*, config2::bias_t*) (.304)': Cannot apply array transformation pragma/directive because of full array load/store. (firmware/nnet_utils/nnet_conv1d_latency.h:81:11)
ERROR: [HLS 200-1715] Encountered problem during source synthesis
```

## Details

I'm using the current master hls4ml branch where the lastest commit is:

```
commit 2e71ff451cc36ce8e7319a92b65a5d9be8bff427 (HEAD -> main, origin/main, origin/HEAD)
Merge: eca1ea37 9d2e6640
Author: Jovan Mitrevski <jmitrevs@fnal.gov>
Date:   Tue May 16 13:55:19 2023 -0500

    Merge pull request #796 from fastmachinelearning/pre-commit-ci-update-config
```

### Steps to Reproduce
I included the `.h5` file of the model [here.](https://www.dropbox.com/s/r6pxc8uttonqgny/QModel_9bit_150.h5?dl=0) 

And a script to convert the model [here. ](https://www.dropbox.com/s/v0gb8s70dkq9sk8/hls_9bit_model.py?dl=0)

You could run the conversion using:
 ```
python hls_9bit_model.py
```

I'm not really sure what's happening here ...

**Comment by jmduarte** [comment]
@Duchstf which Vitis version are you using?

@vloncar may have some guidance on whether the current unrolled conv1d latency implementation is expected to work in Vitis.

I can try to take a look.

**Comment by Duchstf** [comment]
I tested out #815 and it fixes this error. Here are the latency/resources reports if people care:

Latency:

![Screen Shot 2023-06-19 at 11 11 19 AM](https://github.com/fastmachinelearning/hls4ml/assets/35171417/97fdddfd-01b2-450d-bb65-5567dc6829da)

Resources:


![Screen Shot 2023-06-19 at 11 12 00 AM](https://github.com/fastmachinelearning/hls4ml/assets/35171417/166860d0-25b7-4caf-a68a-284d7d78eb87)

The II is still a bit high compared to what I expected, but this is subjected to further optimization. I will also try out what Javier proposes in #811 for the conv layers.

**Comment by vloncar** [comment]
The II is as expected, you need to increase the `ParallelizationFactor` of the two Conv layers to bring the II down.
