### ISSUE TITLE
Vitis HLS support!

### ISSUE THREAD

**Issue by AnttiLukats** [fastmachinelearning/hls4ml#810]
## Prerequisites
none

## Details
support for Vitis-HLS

### New behavior
Vitis-HLS supported

### Motivation
It is always better to use up to date tools

### Parts of hls4ml being affected
all?

**Comment by vloncar** [comment]
It's already there in experimental form. It's is mentioned in the release notes and the docs.

**Comment by AnttiLukats** [comment]
Thanks, good to know it is worked on.
